### ISSUE TITLE
Spacer Block

### ISSUE THREAD

**Issue by shazahm1** [kadencethemes/kadence-blocks#52]
The Spacer block seems to mess up the layout editor display.

**Comment by shazahm1** [comment]
Thisd seems to be the cause:

``` css
.kt-block-spacer {
	position: relative;
	height: 100%;
	border: dashed 1px #eee;
}
```
